---
title: "Week 13 In Class Part 1"
author: "Bella Kintigh"
format: html
message: FALSE
echo: FALSE
---

# Purpose

# Libraries

```{r}
library(here)
library(tidyverse)
library(purrr)
```

# Simple for Loop

```{r}
print(paste("This year is", 2000))

# Put in a for loop
years <- c(2015:2021)

# ------------ Simple loop ----------------
for (i in years) { # set up the for loop where i is the index
  print(paste("This year is", i))
  
}
# --------------- Save the loop ----------------------

#Pre-allocate space for the for loop
# empty matrix that is as long as the years vector
 year_data<-tibble(year =  rep(NA, length(years)),  # column name for year
                   year_name = rep(NA, length(years))) # column name for the year name
year_data


# ------------- Adding complexity -------------------

for (i in 1:length(years)){ # set up the for loop where i is the index
  year_data$year_name[i]<-paste("The year is", years[i]) # loop over i
}
year_data

# ------------- Add in year column ------------------

for (i in 1:length(years)){ # set up the for loop where i is the index
  year_data$year_name[i]<-paste("The year is", years[i]) # loop over year name
  year_data$year[i]<-years[i] # loop over year
}
year_data
```

# Using a loop to read multiple CSV files 

```{r}
testdata <- read_csv(here("Week_13", "Data", "cond_data","011521_CT316_1pcal.csv"))

# point to the location on the computer of the folder
CondPath <- here("Week_13", "Data", "cond_data")

# you can use regex to be more specific if you are looking for certain patterns in filenames
files <- dir(path = CondPath,pattern = ".csv")
files

# Preallocate space for the loop 
# make an empty dataframe that has one row for each file and 3 columns
 cond_data<-tibble(filename =  rep(NA, length(files)),  # column name for year
                   mean_temp = rep(NA, length(files)), # column name for the mean temperature
                   mean_sal = rep(NA, length(files)), # column name for the mean salinity
                   ) # column name for the year name
cond_data

# Make sure it finds the files 
raw_data <- read_csv(paste0(CondPath,"/",files[1])) # test by reading in the first file and see if it works
head(raw_data)

# ------------------- Loop over the raw data ----------------------------------

for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
cond_data$mean_temp[i]<-mean(raw_data$Temperature, na.rm =TRUE)
cond_data$mean_sal[i]<-mean(raw_data$Salinity, na.rm =TRUE)
} 
cond_data
```

# Using purrrr

```{r}
1:10 %>% # a vector from 1 to 10 (we are going to do this 10 times) %>% # the vector to iterate over
  map(rnorm, n = 15)  %>% # calculate 15 random numbers based on a normal distribution in a list 
  map_dbl(mean) # calculate the mean. It is now a vector which is type "double"




# Complex 

# point to the location on the computer of the folder
CondPath <- here("Week_13", "Data", "cond_data")
files <- dir(path = CondPath,pattern = ".csv", full.names = TRUE)
files


data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") %>% # map everything to a dataframe and put the id in a column called filename
  group_by(filename) %>%
  summarise(mean_temp = mean(Temperature, na.rm = TRUE),
            mean_sal = mean(Salinity,na.rm = TRUE))
data
```














